module.exports = [
    // washington
    {
        name: "Crystal Mountain",
        location: "Washington, USA",
        latitude: 46.9358,
        longitude: -121.4737,
        description: "Crystal Mountain is a premier ski resort in Washington with breathtaking views and a variety of terrain suitable for all skill levels.",
        price: 75 
    },
    {
        name: "Mount Baker Ski Area",
        location: "Washington, USA",
        latitude: 48.8575,
        longitude: -121.6620,
        description: "Mount Baker Ski Area is known for its abundant snowfall and challenging terrain, attracting experienced skiers and snowboarders.",
        price: 65 
    },
    {
        name: "Stevens Pass Mountain Resort",
        location: "Washington, USA",
        latitude: 47.7448,
        longitude: -121.0890,
        description: "Stevens Pass Mountain Resort offers a diverse range of trails, terrain parks, and backcountry skiing opportunities.",
        price: 80 
    },
    {
        name: "Snoqualmie Pass",
        location: "Washington, USA",
        latitude: 47.4222,
        longitude: -121.4217,
        description: "Snoqualmie Pass features several ski areas with family-friendly slopes and night skiing options.",
        price: 70 
    },
    {
        name: "White Pass Ski Area",
        location: "Washington, USA",
        latitude: 46.6381,
        longitude: -121.3903,
        description: "White Pass Ski Area is a laid-back resort known for its friendly atmosphere and varied terrain.",
        price: 65 
    },
    {
        name: "Mission Ridge Ski & Board Resort",
        location: "Washington, USA",
        latitude: 47.3094,
        longitude: -120.3991,
        description: "Mission Ridge offers sunny skies, groomed runs, and panoramic views of the Cascade Mountains.",
        price: 70 
    },
    {
        name: "49 Degrees North Ski Resort",
        location: "Washington, USA",
        latitude: 48.2353,
        longitude: -117.5957,
        description: "49 Degrees North is a hidden gem with abundant snowfall and diverse terrain for skiers and snowboarders.",
        price: 60 
    },
    {
        name: "Mount Spokane Ski and Snowboard Park",
        location: "Washington, USA",
        latitude: 47.9189,
        longitude: -117.1035,
        description: "Mount Spokane offers a family-friendly atmosphere and excellent opportunities for skiing and snowboarding.",
        price: 55 
    },
    {
        name: "Hurricane Ridge Ski and Snowboard Area",
        location: "Washington, USA",
        latitude: 47.9691,
        longitude: -123.4945,
        description: "Hurricane Ridge offers breathtaking views of the Olympic Mountains and a range of winter activities.",
        price: 45 
    },
    // misc by country
    {
        name: "Rosa Khutor Alpine Resort",
        location: "Krasnaya Polyana, Russia",
        latitude: 43.6702,
        longitude: 40.2716,
        description: "Rosa Khutor is a modern ski resort with Olympic-standard facilities, offering a diverse range of slopes.",
        price: 55 
    },
    {
        name: "Gudauri",
        location: "Georgia",
        latitude: 42.4662,
        longitude: 44.4876,
        description: "Gudauri is a fast-growing ski resort known for its excellent snow conditions and stunning mountain views.",
        price: 40 
    },
    {
        name: "Grandvalira",
        location: "Andorra",
        latitude: 42.5761,
        longitude: 1.6677,
        description: "Grandvalira is the largest ski resort in the Pyrenees, offering an extensive network of slopes and modern facilities.",
        price: 55 
    },
    {
        name: "Cardrona Alpine Resort",
        location: "South Island, New Zealand",
        latitude: -44.7014,
        longitude: 169.0326,
        description: "Cardrona Alpine Resort offers a mix of terrain for all skill levels and is renowned for its excellent freestyle facilities.",
        price: 80 
    },
    {
        name: "Thredbo",
        location: "New South Wales, Australia",
        latitude: -36.5003,
        longitude: 148.3049,
        description: "Thredbo is Australia's premier ski resort, featuring long runs and a vibrant village atmosphere.",
        price: 85 
    },
    {
        name: "Cerro Catedral",
        location: "San Carlos de Bariloche, Argentina",
        latitude: -41.1676,
        longitude: -71.4284,
        description: "Cerro Catedral is the largest ski resort in South America, offering a wide range of slopes and stunning views of the Andes.",
        price: 70 
    },
    {
        name: "Valle Nevado",
        location: "Chile",
        latitude: -33.3529,
        longitude: -70.2489,
        description: "Valle Nevado is a modern ski resort with excellent snow conditions and extensive terrain for skiers and snowboarders.",
        price: 75
    },
    {
        name: "Oukaimeden",
        location: "Morocco",
        latitude: 31.1767,
        longitude: -7.8000,
        description: "Oukaimeden is a unique ski resort in the Atlas Mountains, offering a thrilling experience in a stunning setting.",
        price: 40
    },
    {
        name: "Antarctica",
        location: "Antarctica",
        latitude: -82.8628,
        longitude: 135.0000,
        description: "Antarctica offers adventurous skiers a once-in-a-lifetime opportunity to ski in a remote and pristine environment.",
        price: 0
    },
// top 100 in world
    {
      name: "Whistler Blackcomb",
      location: "British Columbia, Canada",
      latitude: 50.1163,
      longitude: -122.9574,
      description: "One of North America's largest and most popular ski resorts.",
      price: 80,
    },
    {
      name: "Verbier",
      location: "Valais, Switzerland",
      latitude: 46.0972,
      longitude: 7.2286,
      description: "A world-class resort known for its challenging terrain and vibrant apres-ski scene.",
      price: 100,
    },
    {
      name: "Aspen Snowmass",
      location: "Colorado, USA",
      latitude: 39.2097,
      longitude: -106.9499,
      description: "A premier ski destination with four mountains and diverse terrain.",
      price: 90,
    },
    {
      name: "St. Anton am Arlberg",
      location: "Tyrol, Austria",
      latitude: 47.1304,
      longitude: 10.2683,
      description: "A charming Austrian village with access to extensive ski terrain.",
      price: 110,
    },
    {
      name: "Jackson Hole",
      location: "Wyoming, USA",
      latitude: 43.5878,
      longitude: -110.8274,
      description: "Famous for its challenging slopes and breathtaking Teton mountain views.",
      price: 95,
    },
    {
      name: "Courchevel",
      location: "Savoie, France",
      latitude: 45.4142,
      longitude: 6.6346,
      description: "Part of the Three Valleys, one of the world's largest ski areas.",
      price: 105,
    },
    {
      name: "Niseko United",
      location: "Hokkaido, Japan",
      latitude: 42.8048,
      longitude: 140.6875,
      description: "Renowned for its abundant powder snow and vibrant international atmosphere.",
      price: 85,
    },
    {
      name: "Zermatt",
      location: "Valais, Switzerland",
      latitude: 45.9763,
      longitude: 7.6585,
      description: "Famous for the iconic Matterhorn mountain and extensive ski opportunities.",
      price: 115,
    },
    {
      name: "Chamonix",
      location: "Haute-Savoie, France",
      latitude: 45.9237,
      longitude: 6.8694,
      description: "A legendary resort known for its challenging terrain and alpine beauty.",
      price: 95,
    },
    {
      name: "Vail",
      location: "Colorado, USA",
      latitude: 39.6061,
      longitude: -106.3555,
      description: "One of the largest ski resorts in the USA with a European-style village.",
      price: 100,
    },
    {
      name: "Val d'Isère",
      location: "Savoie, France",
      latitude: 45.4489,
      longitude: 6.9808,
      description: "Part of the Espace Killy ski area, offering extensive slopes and great nightlife.",
      price: 105,
    },
    {
      name: "Park City Mountain Resort",
      location: "Utah, USA",
      latitude: 40.6514,
      longitude: -111.508,
      description: "A massive resort known for its excellent facilities and lively town.",
      price: 85,
    },
    {
      name: "Banff/Lake Louise/Sunshine",
      location: "Alberta, Canada",
      latitude: 51.1784,
      longitude: -115.5708,
      description: "A trio of world-class resorts in the stunning Canadian Rockies.",
      price: 100,
    },
    {
      name: "Heavenly Mountain",
      location: "California/Nevada, USA",
      latitude: 38.9399,
      longitude: -119.9809,
      description: "A beautiful Lake Tahoe resort with breathtaking views and diverse terrain.",
      price: 95,
    },
    {
      name: "Cortina d'Ampezzo",
      location: "Veneto, Italy",
      latitude: 46.5405,
      longitude: 12.1357,
      description: "An elegant Italian resort nestled in the Dolomites.",
      price: 95,
    },
    {
      name: "Big Sky Resort",
      location: "Montana, USA",
      latitude: 45.2856,
      longitude: -111.4017,
      description: "A vast resort offering diverse terrain and stunning views of Lone Peak.",
      price: 90,
    },
    {
      name: "Alta/Snowbird",
      location: "Utah, USA",
      latitude: 40.5885,
      longitude: -111.6392,
      description: "Two iconic resorts known for abundant snowfall and challenging terrain.",
      price: 100,
    },
    {
      name: "Portillo",
      location: "Valparaiso Region, Chile",
      latitude: -32.8339,
      longitude: -70.0795,
      description: "A legendary Andean resort with breathtaking vistas and powder skiing.",
      price: 85,
    },
    {
      name: "Laax",
      location: "Graubünden, Switzerland",
      latitude: 46.8264,
      longitude: 9.2753,
      description: "A modern resort with extensive slopes and a vibrant freestyle scene.",
      price: 95,
    },
    {
      name: "Telluride",
      location: "Colorado, USA",
      latitude: 37.9375,
      longitude: -107.8123,
      description: "A charming mountain town with challenging terrain and stunning views.",
      price: 105,
    },
    {
      name: "Sun Valley",
      location: "Idaho, USA",
      latitude: 43.6807,
      longitude: -114.3637,
      description: "A classic resort with a rich skiing heritage and excellent amenities.",
      price: 95,
    },
    {
      name: "Gstaad",
      location: "Bernese Oberland, Switzerland",
      latitude: 46.4725,
      longitude: 7.2863,
      description: "An upscale resort known for its glamorous atmosphere and picturesque surroundings.",
      price: 120,
    },
    {
      name: "Andermatt",
      location: "Uri, Switzerland",
      latitude: 46.6341,
      longitude: 8.5957,
      description: "A charming Swiss village with access to a wide range of terrain.",
      price: 85,
    },
    {
      name: "Kitzbühel",
      location: "Tyrol, Austria",
      latitude: 47.4467,
      longitude: 12.3928,
      description: "A historic ski town with challenging slopes and a vibrant atmosphere.",
      price: 110,
    },
    {
      name: "Courmayeur",
      location: "Aosta Valley, Italy",
      latitude: 45.7909,
      longitude: 6.9684,
      description: "A picturesque resort with stunning views of Mont Blanc.",
      price: 95,
    },
    {
      name: "Taos Ski Valley",
      location: "New Mexico, USA",
      latitude: 36.5952,
      longitude: -105.4542,
      description: "A unique and challenging resort in the Sangre de Cristo Mountains.",
      price: 85,
    },
    {
      name: "Alyeska Resort",
      location: "Alaska, USA",
      latitude: 60.9703,
      longitude: -149.0986,
      description: "A stunning Alaskan resort with breathtaking views and diverse terrain.",
      price: 90,
    },
    {
      name: "Mont Tremblant",
      location: "Quebec, Canada",
      latitude: 46.1183,
      longitude: -74.5941,
      description: "A lively Quebecois resort with a charming European-style village.",
      price: 95,
    },
    {
      name: "Stowe Mountain Resort",
      location: "Vermont, USA",
      latitude: 44.4654,
      longitude: -72.6874,
      description: "A classic New England resort known for its scenic beauty and challenging runs.",
      price: 100,
    },
    {
      name: "Revelstoke Mountain Resort",
      location: "British Columbia, Canada",
      latitude: 51.0034,
      longitude: -118.2273,
      description: "A mecca for powder enthusiasts with some of North America's best snowfall.",
      price: 95,
    },
    {
      name: "Snowbird",
      location: "Utah, USA",
      latitude: 40.5803,
      longitude: -111.6547,
      description: "A powder paradise with steep terrain and reliable snow conditions.",
      price: 100,
    },
    {
      name: "Grandvalira",
      location: "Andorra",
      latitude: 42.5761,
      longitude: 1.6672,
      description: "The largest ski resort in the Pyrenees, offering a variety of slopes.",
      price: 80,
    },
    {
      name: "Whiteface Mountain",
      location: "New York, USA",
      latitude: 44.3654,
      longitude: -73.8736,
      description: "Home to the 1980 Winter Olympics, featuring challenging runs and stunning views.",
      price: 85,
    },
    {
      name: "Gudauri",
      location: "Georgia",
      latitude: 42.4694,
      longitude: 44.4802,
      description: "A rising star among ski destinations with excellent freeriding opportunities.",
      price: 75,
    },
    {
      name: "Davos",
      location: "Graubünden, Switzerland",
      latitude: 46.8040,
      longitude: 9.8365,
      description: "A premier Alpine resort known for hosting the annual World Economic Forum.",
      price: 110,
    },
    {
      name: "Hemsedal",
      location: "Norway",
      latitude: 60.8586,
      longitude: 8.6039,
      description: "Norway's largest ski resort, offering stunning Scandinavian scenery.",
      price: 90,
    },
    {
      name: "Lech Zürs",
      location: "Vorarlberg, Austria",
      latitude: 47.2093,
      longitude: 10.1432,
      description: "A luxury resort with high-quality slopes and a charming village atmosphere.",
      price: 120,
    },
    {
      name: "Mammoth Mountain",
      location: "California, USA",
      latitude: 37.6308,
      longitude: -119.0325,
      description: "A California gem with a long season and excellent terrain parks.",
      price: 100,
    },
    {
      name: "Mad River Glen",
      location: "Vermont, USA",
      latitude: 44.2081,
      longitude: -72.9169,
      description: "A legendary ski area known for its challenging terrain and no snowboarding policy.",
      price: 80,
    },
    {
      name: "Crans-Montana",
      location: "Valais, Switzerland",
      latitude: 46.3095,
      longitude: 7.4818,
      description: "A vibrant resort with a sunny climate and stunning views of the Swiss Alps.",
      price: 95,
    },
    {
      name: "Åre",
      location: "Jämtland, Sweden",
      latitude: 63.3983,
      longitude: 13.0788,
      description: "Scandinavia's largest ski resort, offering a variety of slopes and an active nightlife.",
      price: 85,
    },
    {
      name: "Engelberg",
      location: "Obwalden, Switzerland",
      latitude: 46.8205,
      longitude: 8.4062,
      description: "A picturesque resort with impressive off-piste and freeride opportunities.",
      price: 100,
    },
    {
      name: "Steamboat Ski Resort",
      location: "Colorado, USA",
      latitude: 40.4572,
      longitude: -106.8048,
      description: "A Western-themed resort with famous Champagne Powder snow.",
      price: 90,
    },
    {
      name: "Sölden",
      location: "Tyrol, Austria",
      latitude: 46.9686,
      longitude: 11.0079,
      description: "A popular resort with extensive skiing and high-altitude slopes.",
      price: 95,
    },
    {
      name: "Snowbasin",
      location: "Utah, USA",
      latitude: 41.2166,
      longitude: -111.8567,
      description: "A hidden gem with uncrowded slopes and stunning mountain vistas.",
      price: 85,
    },
    {
      name: "Tignes",
      location: "Savoie, France",
      latitude: 45.4746,
      longitude: 6.9037,
      description: "Part of the Espace Killy ski area, known for its reliable snow conditions.",
      price: 100,
    },
    {
      name: "Copper Mountain",
      location: "Colorado, USA",
      latitude: 39.5020,
      longitude: -106.1511,
      description: "A family-friendly resort with a variety of terrain and a laid-back atmosphere.",
      price: 90,
    },
    {
      name: "Serre Chevalier",
      location: "Hautes-Alpes, France",
      latitude: 44.9375,
      longitude: 6.6394,
      description: "A large resort with a mix of alpine charm and modern amenities.",
      price: 95,
    },
    {
      name: "Snowshoe Mountain",
      location: "West Virginia, USA",
      latitude: 38.4104,
      longitude: -79.9932,
      description: "A top-notch resort in the Mid-Atlantic region, offering diverse skiing.",
      price: 80,
    },
    {
      name: "Saas-Fee",
      location: "Valais, Switzerland",
      latitude: 46.1139,
      longitude: 7.9297,
      description: "A charming car-free resort with impressive glaciers and a lively village.",
      price: 105,
    },
    {
      name: "Les Deux Alpes",
      location: "Isère, France",
      latitude: 45.0133,
      longitude: 6.1241,
      description: "A popular summer and winter destination with a vibrant après-ski scene.",
      price: 95,
    },
    {
      name: "Grand Targhee",
      location: "Wyoming, USA",
      latitude: 43.7904,
      longitude: -110.9583,
      description: "A hidden gem known for its abundant powder and stunning Teton views.",
      price: 85,
    },
    {
      name: "Alpe d'Huez",
      location: "Isère, France",
      latitude: 45.0915,
      longitude: 6.0689,
      description: "A sunny resort with excellent slopes and the famous Sarenne run.",
      price: 90,
    },
    {
      name: "Mount Bachelor",
      location: "Oregon, USA",
      latitude: 43.9794,
      longitude: -121.6883,
      description: "A volcanic mountain with diverse terrain and a laid-back atmosphere.",
      price: 85,
    },
    {
      name: "Snowmass",
      location: "Colorado, USA",
      latitude: 39.2097,
      longitude: -106.9499,
      description: "Part of Aspen Snowmass, offering a variety of terrain and excellent facilities.",
      price: 100,
    },
    {
      name: "Les Arcs",
      location: "Savoie, France",
      latitude: 45.5729,
      longitude: 6.7931,
      description: "A linked ski area with varied runs and stunning views of the Tarentaise Valley.",
      price: 95,
    },
    {
      name: "Zell am See-Kaprun",
      location: "Salzburg, Austria",
      latitude: 47.3025,
      longitude: 12.7937,
      description: "A scenic resort with access to the Zell am See and Kaprun ski areas.",
      price: 100,
    },
    {
      name: "Copper Mountain",
      location: "Colorado, USA",
      latitude: 39.5020,
      longitude: -106.1511,
      description: "A family-friendly resort with a variety of terrain and a laid-back atmosphere.",
      price: 90,
    },
    {
      name: "Sugarloaf",
      location: "Maine, USA",
      latitude: 45.0311,
      longitude: -70.3133,
      description: "A vast resort with challenging terrain and stunning views of the Carrabassett Valley.",
      price: 85,
    },
    {
      name: "Winter Park",
      location: "Colorado, USA",
      latitude: 39.8868,
      longitude: -105.7626,
      description: "A popular resort with varied terrain and a convenient location near Denver.",
      price: 95,
    },
    {
      name: "Obertauern",
      location: "Salzburg, Austria",
      latitude: 47.2513,
      longitude: 13.5562,
      description: "A high-altitude resort known for its reliable snow and lively après-ski.",
      price: 85,
    },
    {
      name: "Sugarbush Resort",
      location: "Vermont, USA",
      latitude: 44.1353,
      longitude: -72.8972,
      description: "A classic New England resort with diverse terrain and a charming atmosphere.",
      price: 90,
    },
    {
      name: "Les 3 Vallées",
      location: "Savoie, France",
      latitude: 45.3105,
      longitude: 6.5792,
      description: "The world's largest ski area, offering endless slopes and interconnected resorts.",
      price: 110,
    },
    {
      name: "La Grave",
      location: "Hautes-Alpes, France",
      latitude: 45.0410,
      longitude: 6.3246,
      description: "An off-piste paradise with challenging terrain and no marked runs.",
      price: 85,
    },
    {
      name: "Whitefish Mountain Resort",
      location: "Montana, USA",
      latitude: 48.4758,
      longitude: -114.3506,
      description: "A friendly resort with diverse skiing and stunning views of Glacier National Park.",
      price: 90,
    },
    {
      name: "Pila",
      location: "Aosta Valley, Italy",
      latitude: 45.7333,
      longitude: 7.3667,
      description: "A compact resort offering great family skiing and panoramic views of the Alps.",
      price: 85,
    },
    {
      name: "Big White Ski Resort",
      location: "British Columbia, Canada",
      latitude: 49.7247,
      longitude: -118.9353,
      description: "A popular resort known for its powder skiing and family-friendly atmosphere.",
      price: 95,
    },
    {
      name: "Crans Montana",
      location: "Valais, Switzerland",
      latitude: 46.3121,
      longitude: 7.4818,
      description: "A vibrant resort with a sunny climate and stunning views of the Swiss Alps.",
      price: 100,
    },
    {
      name: "Les Gets",
      location: "Haute-Savoie, France",
      latitude: 46.1605,
      longitude: 6.6730,
      description: "A charming resort with traditional Alpine architecture and great skiing.",
      price: 90,
    },
    {
      name: "Wengen",
      location: "Bernese Oberland, Switzerland",
      latitude: 46.6033,
      longitude: 7.9231,
      description: "A car-free resort with classic Swiss charm and access to the Jungfrau region.",
      price: 105,
    },
    {
      name: "St. Moritz",
      location: "Graubünden, Switzerland",
      latitude: 46.4983,
      longitude: 9.8355,
      description: "A glamorous resort with world-class skiing and upscale amenities.",
      price: 110,
    },
    {
      name: "La Plagne",
      location: "Savoie, France",
      latitude: 45.5052,
      longitude: 6.6867,
      description: "Part of the Paradiski area, offering extensive skiing and great snow conditions.",
      price: 95,
    },
    {
      name: "Les Houches",
      location: "Haute-Savoie, France",
      latitude: 45.8881,
      longitude: 6.8030,
      description: "A picturesque resort with stunning views of the Mont Blanc massif.",
      price: 85,
    },
    {
      name: "Brian Head Resort",
      location: "Utah, USA",
      latitude: 37.6936,
      longitude: -112.8492,
      description: "A family-friendly resort with diverse terrain and reliable snow.",
      price: 90,
    },
    {
      name: "Grindelwald",
      location: "Bernese Oberland, Switzerland",
      latitude: 46.6248,
      longitude: 8.0345,
      description: "A charming Swiss village with access to the Jungfrau ski region.",
      price: 95,
    },
    {
      name: "Cervinia",
      location: "Aosta Valley, Italy",
      latitude: 45.9369,
      longitude: 7.6255,
      description: "A high-altitude resort with stunning views of the Matterhorn.",
      price: 100,
    },
    {
      name: "Flaine",
      location: "Haute-Savoie, France",
      latitude: 46.0057,
      longitude: 6.6926,
      description: "A modernist resort with convenient slopeside accommodations.",
      price: 85,
    },
    {
      name: "Schweitzer Mountain Resort",
      location: "Idaho, USA",
      latitude: 48.3687,
      longitude: -116.6217,
      description: "A hidden gem offering diverse skiing and stunning views of Lake Pend Oreille.",
      price: 90,
    },
    {
      name: "Arosa",
      location: "Graubünden, Switzerland",
      latitude: 46.7755,
      longitude: 9.6792,
      description: "A peaceful resort with great off-piste and a relaxing atmosphere.",
      price: 95,
    },
    {
      name: "Hakuba",
      location: "Nagano, Japan",
      latitude: 36.6902,
      longitude: 137.8422,
      description: "A popular Japanese resort with deep powder and access to multiple ski areas.",
      price: 105,
    },
    {
      name: "Cardrona Alpine Resort",
      location: "Otago, New Zealand",
      latitude: -44.7325,
      longitude: 168.8505,
      description: "A top-notch resort in the Southern Hemisphere offering great snow conditions.",
      price: 85,
    },
    {
      name: "Kirkwood Mountain Resort",
      location: "California, USA",
      latitude: 38.6848,
      longitude: -120.0652,
      description: "A hidden gem known for its deep snow and challenging terrain.",
      price: 95,
    },
    {
      name: "Livigno",
      location: "Lombardy, Italy",
      latitude: 46.5325,
      longitude: 10.1467,
      description: "A duty-free resort with a lively après-ski scene and excellent snow reliability.",
      price: 90,
    },
    {
      name: "Snowbird",
      location: "Utah, USA",
      latitude: 40.5803,
      longitude: -111.6547,
      description: "A powder paradise with steep terrain and reliable snow conditions.",
      price: 100,
    },
    {
      name: "Kicking Horse Mountain Resort",
      location: "British Columbia, Canada",
      latitude: 51.3000,
      longitude: -117.0323,
      description: "A resort known for its steep chutes and stunning views of the Canadian Rockies.",
      price: 95,
    },
    {
      name: "Sun Peaks Resort",
      location: "British Columbia, Canada",
      latitude: 50.8812,
      longitude: -119.8856,
      description: "A family-friendly resort with extensive terrain and a welcoming atmosphere.",
      price: 90,
    },
    {
      name: "La Rosière",
      location: "Savoie, France",
      latitude: 45.6209,
      longitude: 6.8585,
      description: "A family-friendly resort with access to the Espace San Bernardo ski area.",
      price: 85,
    },
    {
      name: "Solitude Mountain Resort",
      location: "Utah, USA",
      latitude: 40.6198,
      longitude: -111.5910,
      description: "A peaceful resort known for its uncrowded slopes and stunning scenery.",
      price: 90,
    },
    {
      name: "Grand Massif",
      location: "Haute-Savoie, France",
      latitude: 46.0278,
      longitude: 6.6856,
      description: "A vast ski area with interconnected villages and diverse terrain.",
      price: 95,
    },
    {
      name: "Mont-Sainte-Anne",
      location: "Quebec, Canada",
      latitude: 47.0843,
      longitude: -70.9098,
      description: "A popular resort with great snow conditions and beautiful views of the St. Lawrence River.",
      price: 90,
    },
    {
      name: "Grimentz",
      location: "Valais, Switzerland",
      latitude: 46.1756,
      longitude: 7.5786,
      description: "A charming Swiss resort with traditional alpine architecture and excellent skiing.",
      price: 85,
    },
    {
      name: "Bansko",
      location: "Blagoevgrad Province, Bulgaria",
      latitude: 41.8359,
      longitude: 23.4845,
      description: "An affordable resort with modern facilities and stunning Pirin Mountain views.",
      price: 80,
    },
    {
      name: "Meribel",
      location: "Savoie, France",
      latitude: 45.4144,
      longitude: 6.5652,
      description: "A central resort in Les Trois Vallées, offering access to a vast ski area.",
      price: 95,
    },
    {
      name: "Soldeu",
      location: "Andorra",
      latitude: 42.5765,
      longitude: 1.6675,
      description: "A lively resort in the Grandvalira ski area, popular for its lively après-ski.",
      price: 90,
    },
    {
      name: "Arabba",
      location: "Veneto, Italy",
      latitude: 46.4988,
      longitude: 11.8753,
      description: "A charming village in the Dolomiti Superski area, known for its stunning scenery.",
      price: 95,
    },
    {
      name: "Hakuba",
      location: "Nagano, Japan",
      latitude: 36.6902,
      longitude: 137.8422,
      description: "A popular Japanese resort with deep powder and access to multiple ski areas.",
      price: 100,
    },
    {
      name: "Bad Gastein",
      location: "Salzburg, Austria",
      latitude: 47.1140,
      longitude: 13.1309,
      description: "A historic spa town with access to the extensive Ski Amadé region.",
      price: 90,
    },
    {
      name: "Sierra-at-Tahoe",
      location: "California, USA",
      latitude: 38.8005,
      longitude: -120.0804,
      description: "A laid-back resort known for its excellent tree skiing and friendly atmosphere.",
      price: 85,
    },
    {
      name: "Pamporovo",
      location: "Smolyan Province, Bulgaria",
      latitude: 41.6565,
      longitude: 24.6964,
      description: "A sunny resort with a friendly ambiance, perfect for beginners and families.",
      price: 80,
    }
  ];